#!/usr/bin/env bash

export BASEDIR=$(dirname $(realpath $0))
export VENV=$BASEDIR/venv
export VENVBIN=$VENV/bin/activate
export ICON=$BASEDIR/assets/icon.png
export REQUIREMENTS=$BASEDIR/requirements
export LAUNCHER=$BASEDIR/launch
export TITLE="STRINSTALL"


function yes_or_no () {
    while true; do
        printf "\nStrjectories Installation\n"
        read -p "Create Desktop Icon? [y/n]: " yn
        case $yn in
            [Yy]*) return 0 ;;  
            [Nn]*) return 1 ;;
        esac
    done
}

function desktop_icon () {
    > $HOME/Desktop/STRJECTORIES.desktop
    echo [Desktop Entry] >> $HOME/Desktop/STRJECTORIES.desktop
    echo Name=STRJECTORIES >> $HOME/Desktop/STRJECTORIES.desktop
    echo Icon=$ICON >> $HOME/Desktop/STRJECTORIES.desktop
    echo Exec=$LAUNCHER >> $HOME/Desktop/STRJECTORIES.desktop
    echo Type=Application >> $HOME/Desktop/STRJECTORIES.desktop
    echo Encoding=UTF-8 >> $HOME/Desktop/STRJECTORIES.desktop
    echo Terminal=false >> $HOME/Desktop/STRJECTORIES.desktop
    echo "Categories=None;" >> $HOME/Desktop/STRJECTORIES.desktop
    return 0
}


if [[ $DESKTOP_SESSION == *"mate"* ]]; then
    if [ ! -f "$VENVBIN" ]; then
        mate-terminal --title $TITLE -x sh -c "python3 -m venv $VENV && 
                                                . $VENVBIN && 
                                                pip install -r $REQUIREMENTS &&
                                                $(declare -f $yes_or_no); yes_or_no &&
                                                $(declare -f $desktop_icon); desktop_icon
                                                "
                                                
    else
        mate-terminal --title $TITLE -x sh -c ". $VENVBIN && 
                                                pip install -r $REQUIREMENTS &&
                                                $(declare -f $yes_or_no); yes_or_no &&
                                                $(declare -f $desktop_icon); desktop_icon
                                                "
    fi
        
else
    if [[ $DESKTOP_SESSION == *"LXDE"* ]]; then
        if [ ! -f "$VENVBIN" ]; then
            lxterminal --title=$TITLE -e "export ICON=$ICON && 
                                            export LAUNCHER=$LAUNCHER && 
                                            $(declare -f $yes_or_no); yes_or_no && 
                                            $(declare -f $desktop_icon); desktop_icon && 
                                            sh -c 'python3 -m venv '$VENV' && 
                                                . '$VENVBIN' && 
                                                pip install -r '$REQUIREMENTS' 
                                                '
                                            "
            
        else
            lxterminal --title=$TITLE -e "export ICON=$ICON && 
                                            export LAUNCHER=$LAUNCHER && 
                                            $(declare -f $yes_or_no); yes_or_no && 
                                            $(declare -f $desktop_icon); desktop_icon && 
                                            sh -c '. '$VENVBIN' && 
                                                pip install -r '$REQUIREMENTS' 
                                                '
                                            "
        fi
    fi
fi
