#!/usr/bin/env bash

export BASEDIR=$(dirname $(realpath $0))
export VENV=$BASEDIR/venv
export VENVBIN=$VENV/bin/activate
export ICON=$BASEDIR/assets/icon.png
export REQUIREMENTS=$BASEDIR/requirements.txt
export LAUNCHER=$BASEDIR/launch
export TITLE="STRINSTALL"

export DESKTOP_LAUNCHER=$HOME/Desktop/STRJECTORIES.desktop
export AUTO_LAUNCHER=$HOME/.config/autostart/STRJECTORIES.desktop


export Q0="Create Desktop Icon?"
export Q1="Create Autostart File?"
export FINISH_MSG='INFO: Strjectories Installation complete. Press Return to exit.'

function yes_or_no {
    while true; do
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0 ;;  
            [Nn]*) return 1 ;;
        esac
    done
}

function launcher {
    > $1
    echo [Desktop Entry] >> $1
    echo Name=STRJECTORIES >> $1
    echo Icon=$ICON >> $1
    echo Exec=$LAUNCHER >> $1
    echo Type=Application >> $1
    echo Encoding=UTF-8 >> $1
    echo Terminal=false >> $1
    echo "Categories=None;" >> $1
    return 0
}


if [[ $DESKTOP_SESSION == *"LXDE"* ]]; then
    if [ ! -f "$VENVBIN" ]; then
        lxterminal --title=$TITLE -e "  sh -c 'python3 -m venv '$VENV' && 
                                            . '$VENVBIN' && 
                                            pip install -r '$REQUIREMENTS' ' &&

                                        export ICON=$ICON && 
                                        export LAUNCHER=$LAUNCHER && 
                                        $(declare -f $yes_or_no); yes_or_no '$Q0' && 
                                        $(declare -f $launcher); launcher $DESKTOP_LAUNCHER;
                                        $(declare -f $yes_or_no); yes_or_no '$Q1' && 
                                        $(declare -f $launcher); launcher $AUTO_LAUNCHER %% 
                                        echo $FINISH_MSG &&
                                        read x;
                                        "
        
    else
        lxterminal --title=$TITLE -e "  sh -c '. '$VENVBIN' && 
                                            pip install -r '$REQUIREMENTS' ' &&

                                        export ICON=$ICON && 
                                        export LAUNCHER=$LAUNCHER && 
                                        $(declare -f $yes_or_no); yes_or_no '$Q0' && 
                                        $(declare -f $launcher); launcher $DESKTOP_LAUNCHER;
                                        $(declare -f $yes_or_no); yes_or_no '$Q1' && 
                                        $(declare -f $launcher); launcher $AUTO_LAUNCHER &&
                                        echo $FINISH_MSG &&
                                        read x; 
                                        "
    fi
else
    if [ ! -f "$VENVBIN" ]; then
        x-terminal-emulator -title $TITLE -e "sh -c 'python3 -m venv $VENV && 
                                                    . $VENVBIN && 
                                                    pip install -r $REQUIREMENTS &&
                                                    
                                                    $(declare -f $yes_or_no); yes_or_no $Q0 &&
                                                    $(declare -f $launcher); launcher $DESKTOP_LAUNCHER;
                                                    $(declare -f $yes_or_no); yes_or_no $Q1 &&
                                                    $(declare -f $launcher); launcher $AUTO_LAUNCHER;
                                                    echo $FINISH_MSG &&
                                                    read x;
                                                    '
                                                "
    else
        x-terminal-emulator -title $TITLE -e "sh -c '. $VENVBIN && 
                                                    pip install -r $REQUIREMENTS &&
                                                    
                                                    $(declare -f $yes_or_no); yes_or_no $Q0 &&
                                                    $(declare -f $launcher); launcher $DESKTOP_LAUNCHER;
                                                    $(declare -f $yes_or_no); yes_or_no $Q1 &&
                                                    $(declare -f $launcher); launcher $AUTO_LAUNCHER &&
                                                    echo $FINISH_MSG &&
                                                    read x; 
                                                    '
                                                "                              
    fi
    
fi
