#!/usr/bin/env bash

basedir=$(dirname $(realpath $0))
scriptdir=scripts
main=$basedir/$scriptdir/main.py
venv=$basedir/venv/bin/activate
geo=87x13+0+635
title="STRWHAT"
desktop=$DESKTOP_SESSION

if [[ $DESKTOP_SESSION == *"LXDE"* ]]; then
    lxterminal --geometry=$geo --title=$title -e 'sh -c ". '$venv' && python3 '$main'; bash";'
else
    x-terminal-emulator -title $title -geometry $geo -e 'sh -c ". '$venv' && python3 '$main'; bash";'  
fi